-- Employee Directory Schema

-- Drop existing tables from previous project
DROP TABLE IF EXISTS PERSON;
DROP TABLE IF EXISTS HOME;
DROP TABLE IF EXISTS CAR;

-- Drop Employee Directory tables if they exist
DROP TABLE IF EXISTS EMPLOYEE;
DROP TABLE IF EXISTS DEPARTMENT;

-- Create Department table first (referenced by Employee)
CREATE TABLE DEPARTMENT (
  DEPT_NUM BIGINT NOT NULL AUTO_INCREMENT,
  DEPT_NAME VARCHAR(255) NOT NULL,
  DEPT_MANAGER_ID BIGINT,
  PRIMARY KEY (DEPT_NUM)
);

-- Create Employee table
CREATE TABLE EMPLOYEE (
  EMP_NUM BIGINT NOT NULL AUTO_INCREMENT,
  FIRST_NAME VARCHAR(255) NOT NULL,
  LAST_NAME VARCHAR(255) NOT NULL,
  TITLE VARCHAR(255),
  PHONE_NUMBER VARCHAR(20),
  EMAIL VARCHAR(255),
  HIRE_DATE DATE,
  MANAGER_ID BIGINT,
  DEPT_NUM BIGINT,
  PRIMARY KEY (EMP_NUM),
  FOREIGN KEY (MANAGER_ID) REFERENCES EMPLOYEE(EMP_NUM),
  FOREIGN KEY (DEPT_NUM) REFERENCES DEPARTMENT(DEPT_NUM)
);

-- Add foreign key constraint for department manager (after Employee table exists)
ALTER TABLE DEPARTMENT ADD CONSTRAINT FK_DEPT_MANAGER 
  FOREIGN KEY (DEPT_MANAGER_ID) REFERENCES EMPLOYEE(EMP_NUM);

-- Create indexes for performance
CREATE INDEX IDX_EMP_MANAGER ON EMPLOYEE(MANAGER_ID);
CREATE INDEX IDX_EMP_DEPT ON EMPLOYEE(DEPT_NUM);
CREATE INDEX IDX_EMP_EMAIL ON EMPLOYEE(EMAIL);
CREATE INDEX IDX_DEPT_NAME ON DEPARTMENT(DEPT_NAME);

-- Ensure sequence exists for auto-generation
DROP SEQUENCE IF EXISTS hibernate_sequence;
CREATE SEQUENCE hibernate_sequence START WITH 1;